[project]
name = "django-yt-clone"
version = "0.1.0"
description = "A simple YT Clone built with Django"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "dotenv>=0.9.9",
]
